import { z } from 'zod'
import { BookingWithNamesSchema } from './booking.model'

export const DashboardKPIsSchema = z.object({
    average_rating: z.number().nullable().optional(),
    target_pct: z.number().nullable().optional(),
    today_revenue: z.number(),
    yesterday_revenue: z.number(),
    today_bookings: z.number().int(),
    today_walkins: z.number().int(),
    bookings_by_source: z.record(z.string(), z.number()).optional(),
    today_customers: z.number().int(),
    today_new_customers: z.number().int(),
    monthly_revenue: z.number(),
    monthly_expenses: z.number().optional(),
    today_expenses: z.number().optional(),
    net_profit: z.number().optional(),
    monthly_bookings: z.number().int(),
    monthly_new_customers: z.number().int(),
    repeat_rate: z.number(),
    avg_bill: z.number(),
    active_employees: z.number().int(),
    pending_bookings: z.number().int(),
    waitlist_count: z.number().int(),
    total_waitlist: z.number().int().optional(),
    total_customers: z.number().int().optional(),
    queue_count: z.number().int().optional(),
    low_stock_count: z.number().int(),
    leaked_amount: z.number(),
    mrr_monthly: z.number().optional(),
    month_bookings: z.number().int().optional(),
    revenue_trend: z.array(z.object({
        date: z.string(),
        label: z.string(),
        revenue: z.number(),
        expenses: z.number().default(0),
        bookings: z.number().int(),
        online: z.number().int(),
        walkin: z.number().int(),
    })),
    booking_trend: z.array(z.object({
        label: z.string(),
        online: z.number(),
        walkin: z.number(),
        expected: z.number(),
    })).optional(),
    top_services: z.array(z.object({
        name: z.string(),
        count: z.number().int(),
        revenue: z.number(),
    })),
    peak_hours: z.array(z.object({
        hour: z.number().int(),
        label: z.string(),
        count: z.number().int(),
    })),
    recent_bookings: z.array(BookingWithNamesSchema),
    funnel_stages: z.object({
        confirmed: z.number().int(),
        arrived: z.number().int(),
        in_service: z.number().int(),
        completed: z.number().int(),
        paid: z.number().int(),
    }).optional(),
    staff_utilization: z.array(z.object({
        name: z.string(),
        booked: z.number(),
        booked_count: z.number().int().optional(),
        idle: z.number(),
    })).optional(),
    payment_breakdown: z.record(z.string(), z.number()).optional(),
    engagement_metrics: z.object({
        online: z.object({ today: z.number(), week: z.number(), month: z.number(), quarter: z.number() }),
        customers: z.object({ today: z.number(), week: z.number(), month: z.number(), quarter: z.number() }),
        repeat_rate: z.object({ today: z.number(), week: z.number(), month: z.number(), quarter: z.number() }),
        waitlist: z.object({ today: z.number(), week: z.number(), month: z.number(), quarter: z.number() }),
        sparklines: z.object({
            today: z.record(z.string(), z.array(z.object({ value: z.number() }))),
            daily: z.record(z.string(), z.array(z.object({ value: z.number() }))),
        }).optional(),
    }).optional(),
    peak_metrics: z.object({
        today: z.array(z.object({ hour: z.number(), label: z.string(), count: z.number() })),
        week: z.array(z.object({ hour: z.number(), label: z.string(), count: z.number() })),
        month: z.array(z.object({ hour: z.number(), label: z.string(), count: z.number() })),
        quarter: z.array(z.object({ hour: z.number(), label: z.string(), count: z.number() })),
    }).optional(),
    subscription: z.object({
        status: z.string(),
        trial_end: z.string().nullable(),
        end_date: z.string().nullable(),
        plans: z.object({ display_name: z.string(), plan_key: z.string(), price: z.number().optional() }).nullable(),
    }).nullable().optional(),
})
export type DashboardKPIs = z.infer<typeof DashboardKPIsSchema>
